export const SIGN_UP_ACTION = "SIGN_UP_ACTION"
export const SIGN_IN_ACTION = "SIGN_IN_ACTION"
export const SIGNED_IN_ACTION = "SIGNED_IN_ACTION"
export const FORGOT_ACTION = "FORGOT_ACTION"

export const SET_ALERT = "SET_ALERT"
export const RESET_ALERT = "RESET_ALERT"